version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_LOOPBACK_USERS=none
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    hostname: rabbitmq  # Important pour la résolution DNS

networks:
  backend:
    external: true     # Indique que le network est externe